apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-subscriber-app
  labels:
    app: message-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-subscriber
  template:
    metadata:
      labels:
        app: message-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "message-subscriber"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: message-subscriber
        image: dzbuild.azurecr.io/message-subscriber:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env: 
          - name: "PORT"
            value: "80"
          - name: "APP"
            value: "234"