apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-receiver-app
  labels:
    app: message-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-receiver
  template:
    metadata:
      labels:
        app: message-receiver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "message-receiver"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: message-receiver
        image: dzbuild.azurecr.io/message-receiver:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env: 
          - name: "PORT"
            value: "80"
          - name: "APP"
            value: "234"